name: Build Ops

on:
  push:
    branches:
      - main
    paths:
      - "src/py/flwr_experimental/ops/**"
  pull_request:
    branches:
      - main
    paths:
      - "src/py/flwr_experimental/ops/**"

jobs:
  test_ops:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.9
      - name: Install build tools
        run: |
          python -m pip install -U pip==21.1.1
          python -m pip install -U setuptools==56.2.0
          python -m pip install -U poetry==1.1.6
          poetry config virtualenvs.create false
      - name: Install dependencies (mandatory + optional)
        run: |
          python -m poetry install --extras "ops"
      - name: Lint + Test (isort/black/mypy/pylint/pytest)
        run: ./dev/test-ops.sh
